version: "3.9"

x-defaults: &x-defaults
  image: local
  build: .
  stdin_open: true
  tty: true
  depends_on:
    - postgres
    - rabbitmq
    - memcached

services:
  backend:
    # command: python ./app/manage.py runserver
    container_name: backend
    ports:
      - "8000:8000"
    <<: *x-defaults

  celery:
    command: celery -A settings worker -l info --autoscale=0,10
    container_name: celery
    <<: *x-defaults

  celerybeat:
    command: celery -A settings beat -l info
    container_name: celerybeat
    <<: *x-defaults

  memcached:
    image: memcached:1.6.9
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
    depends_on:
      - rabbitmq


  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  db_data: {}

