# Generated by Django 4.1.6 on 2023-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
