# Generated by Django 4.1.6 on 2023-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='city',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
