# Generated by Django 4.1.6 on 2023-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_rename_surname_source_source_url_remove_source_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
