# Generated by Django 4.1.6 on 2023-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_alter_rate_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('request_method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')],
                                                    default='GET', max_length=255)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Hryvnia')], default=1),
        ),
    ]
