# Generated by Django 4.1.6 on 2023-03-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_requestresponselog_alter_rate_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='requestresponselog',
            options={'verbose_name': 'Request, Response, Log', 'verbose_name_plural': 'Request, Response, Log'},
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='request_method',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='time',
            field=models.FloatField(),
        ),
    ]
