# Generated by Django 4.1.6 on 2023-03-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_alter_rate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(max_length=25),
        ),
    ]
