# Generated by Django 4.1.6 on 2023-03-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_alter_rate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
